name: build-test-dotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Terraform
    
    steps:
    
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - run: terraform init
    
    - id: plan
      run: terraform plan 

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
